# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Trigger

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      -name: pull
       run: docker pull ghcr.io/baksha97/python-gcp-deploy-template:main
       with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: "3.8"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     pip install -r requirements.txt --upgrade
    # - name: Run it
    #   run: |
    #     python ./src/main.py
    # - name: Test with pytest
    #   run: |
    #     pytest
